version: '3.4'

services:
  proxy:
    build:
      context: ./proxy
    command: --api
    ports:
      - ${UI_PORT}:8080
    volumes:
      - ${DIRECTORY}/proxy/config.dev.toml:/etc/traefik/traefik.toml
