version: '3.4'

services:
  proxy:
    image: digitalstate/proxy:0.18.0
    environment:
      CONSUL_HTTP_TOKEN: ${DISCOVERY_TOKEN}
    ports:
      - ${PORT}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      default:
        aliases:
          - proxy_proxy

networks:
  default: ~
