version: '2'

services:
    proxy:
        image: jwilder/nginx-proxy:alpine
        ports:
            - '${PORT}:80'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
    default: ~
