version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    environment:
      SERVICE_IGNORE: 'true'
    ports:
      - '${PORT}:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default: ~
